<div class="search-form">
<h1>Je recherche</h1>
<form method="GET">
		<input type="hidden" value="search" name="page">
		<input type="text" class="search-input" name="name" id="name" placeholder="titre du livre" />
		<input type="text" class="search-input" name="author" id="author" placeholder="auteur" />
		<input type="text" class="search-input" name="country" id="country" placeholder="pays" />
		<select name="gender" class="search-input" id="gender">
						<option value="">Selectionner un genre</option>
						<?php foreach ($genders AS $gender) : ?>
							<option><?=$gender?></option>
						<?php endforeach; ?>
					</select>
		<p class="numbers" ><span>Publication:</span> de</p>
		<input type="number" class="search-input-numbers" name="year1" id="year1" placeholder="année" />
		<p class="numbers">à</p>
		<input type="number" class="search-input-numbers" name="year2" id="year2" placeholder="année" />
		<input type="text" class="search-input" name="editorial" id="editorial" placeholder="editorial" />
		<input type="text" class="search-input" name="isbn" id="isbn" placeholder="ISBN" />
		<p class="numbers" ><span>Prix:</span> de</p>
		<input type="number" class="search-input-numbers" name="price1" id="price1" placeholder="prix min" />
		<p class="numbers">€ à</p>
		<input type="number" class="search-input-numbers" name="price2" id="price2" placeholder="prix max" />
		<p class="numbers">€</p>
		<input type="submit" class="search-button" value="Rechercher">
	</form>
	<div id="resultats">
		<?php require('apps/search_elem.php'); ?>
	</div>
</div>
