<div class="results">
	
	<img class="float-left" src="./public/img/book.svg" width="80px" alt="">
	<div class="descriptions">
		<h2><?=$book->getName()?></h2>
		<div class="clearfix"></div>
		<h4><span><?=$book->getAuthor()?></span> - <?=$book->getCountry()?> - <?=$book->getYear()?></h4>
		<h3><?=$book->getPrice()?> €</h3>
		<p><?=$book->getEditorial()?></p>
	</div>
	<div class="clearfix"></div>

</div>