<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		
		<title>Recherche</title>
		<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
		<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
		<style>
		
			*{
				box-sizing: border-box;
			}
			body{
				font-family: 'Raleway', sans-serif;
				color:white;
				background-color: #0376BA;

			}

			h2{
				font-size: 55px;
				color: white;
				padding-bottom: 0px;
				margin-top: 0px;
			}

			.search-form{
				width:600px;
				margin: 0 auto;
				margin-top: 10%;
			}
			.search-input{
				padding: 10px;
				width:600px;
				background-color: #0376BA;
				border: 1px solid white;
				font-size: 20px;
				color: white;
			}

			.search-button{
				margin-top: 10px;
				border:0;
				background-color: white;
				color:#0376BA;
				padding: 10px;
				width:600px;
				transition: all 0.5s ease;

			}

			.search-button:hover{
				background-color: #2EA2E6;
				color:white;

			}

			.footer{
				background-color: #2EA2E6;
				text-align: center;
				position: absolute;
				bottom:0px;
				width:99%;
			}

			.results{
				background-color: #1087CE;
				padding:10px;
			}
			.float-left{
				float: left;
				vertical-align: middle;
			}

			.float-left h2{
				margin-top: 0px;
			}
			.clearfix{
				clear: both;
			}
			.descriptions{
				float: left;
				overflow: hidden;

			}
		</style>

	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>
	</body>
</html>