<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		
		<title>Recherche</title>
		
		<script src="public/scripts/jquery-3.1.1.min.js"></script>
		<script type="text/javascript" src="public/scripts/script.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
		<style>
		
			*{
				box-sizing: border-box;
			}
			body{
				font-family: 'Raleway', sans-serif;
				color:white;
				background-color: #0376BA;

			}
			
			h1{
				font-weight: normal;
				font-size: 55px;
			}
			h2{
				font-size: 25px;
				color: white;
				padding-bottom: 0px;
				margin-top: 0px;
			}

			h4{
				font-size: 11px;
				text-transform: uppercase;
			}

			.search-form{
				width:600px;
				margin: 0 auto;
				margin-top: 10%;
			}
			.search-input{
				padding: 10px;
				width:600px;
				background-color: #0376BA;
				border: 1px solid white;
				font-size: 20px;
				color: white;
				margin-bottom: 5px;
			}

			.search-input:focus{
				
				border: 1px solid #2EA2E6;
				
			}

			.search-input-numbers{
				padding: 10px;
				width:100px;
				background-color: #0376BA;
				border: 1px solid white;
				font-size: 20px;
				color: white;
				margin-bottom: 5px;
				display: inline-block;
			}
			.numbers{
				display: inline-block;

			}

			.search-button{
				margin-top: 20px;
				margin-bottom: 50px;
				border:0;
				background-color: white;
				color:#0376BA;
				padding: 10px;
				width:600px;
				transition: all 0.5s ease;

			}

			.search-button:hover{
				background-color: #2EA2E6;
				color:white;

			}

			*::-webkit-input-placeholder {
 			   color: #2EA2E6;
 			   font-size: 13px;
			}

			.footer{
				background-color: #2EA2E6;
				text-align: center;
				position: relative;
				bottom:0px;
				width:99%;
			}
			span{
				font-weight: 800;
			}

			.results{
				margin-top: 10px;
				background-color: #1087CE;
				padding:10px;
			}
			.float-left{
				float: left;
				vertical-align: middle;
			}

			.float-left h2{
				margin-top: 0px;
			}
			.clearfix{
				clear: both;
			}
			.descriptions{
				float: left;
				overflow: hidden;
				margin-left: 10px;

			}
		</style>

	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>
	</body>
</html>